services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_app
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/logs/myapp
      - ./keys:/var/www/keys
      - ./ssl/openssl_myapp.cnf:/etc/ssl/openssl_myapp.cnf
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - App_Network
    env_file:
      - .env

  db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: rapid
    volumes:
      - /mnt/mydrive:/data/db
    ports:
      - "27017:27017"
    networks:
      - App_Network

volumes:
  db_data:
    driver: local

networks:
  App_Network:
    driver: bridge
