FROM php:8.0-apache

# Install necessary extensions and tools
RUN apt-get update && apt-get install -y \
    libonig-dev \
    libssl-dev \
    libgmp-dev \
    git \
    zip \
    unzip \
    curl \
    python3 \
    python3-pip \
    && docker-php-ext-install \
    mbstring \
    && docker-php-ext-enable \
    mbstring \ 
    && pecl install mongodb \
    && docker-php-ext-enable mongodb

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy custom Apache configuration
COPY apache-php/config.conf /etc/apache2/conf-available/custom-config.conf

# Adjust permissions for the Apache configuration file
RUN chown root:root /etc/apache2/conf-available/custom-config.conf \
    && chmod 644 /etc/apache2/conf-available/custom-config.conf

# Enable the new configuration
RUN a2enconf custom-config

# Copy custom php.ini file
COPY apache-php/php.ini /usr/local/etc/php/php.ini

# Set working directory
WORKDIR /var/www/html

# Copy the app directory to the container
COPY ./html /var/www/html

# Set ownership and permissions for /var/www/html
RUN chown -R root:root /var/www/html \
    && chmod -R 755 /var/www/html

# Install Composer dependencies
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Expose port 80
EXPOSE 80

# Start Apache in the foreground as root
CMD ["apache2-foreground"]
